### ISSUE TITLE
[Storage] Exporting 2 Byte Values results in writing 4 Bytes

### ISSUE THREAD

**Issue by rrcomtech** [hyrise-mp-22-23/hyrise#97]
## Problem

Currently, data that is smaller than 32 Bit (4 Byte) is compressed to 16 or 8 Bit. In the current playground setup, this usually happens in a compression to 16 Bit. Afterwards, it should be written to the file with no more than the number of bytes the compression resulted in.

Nevertheless, it showed that the data is always resulting in a 4 Byte write.

## Proposed Solution

Change the `export_value(..)`  function in a way it allows to export less than 32 Bit.
 
Keep in mind, that the mapping might have to be changed for that, since now values can be either of the compression types (not anymore only 32 Bit).

**Comment by Bouncner** [comment]
Is this done?

**Comment by phoeinx** [comment]
Hi @rrcomtech - thanks for checking this out - which data exactly are you talking about? Are you referring to the data of the dictionary and attribute vectors? 
Could you perhaps add some screenshots or code snippets explaining where this breaks for easier understanding/reproducibility?

Re your Proposed Solution:
re: changing `export_value()`
- the `export_value()` function already exports only <char *> vectors (uint8_t typed vectors), so I am not sure how the mentioned problems could stem from it / what you propose to implement is already implemented?

```cpp
template <typename T>
void export_value(std::ofstream& ofstream, const T& value) {
  ofstream.write(reinterpret_cast<const char*>(&value), sizeof(T));
}
```

> Keep in mind, that the mapping might have to be changed for that, since now values can be either of the compression types (not anymore only 32 Bit).

I don't think that we can currently only map attribute vectors with compression type `uint32_t`, apparently we can however only map a specific combination of dictionary data type and attribute vector data type. 

When you look into the current code on `file_format_refactored` in `map_chunk_from_disk` where we read the attribute and dictionary vectors, they are currently still hard-coded to uint32_t and uint16_t. The relevant part being the calculation of bytes to memcpy -> `dictionary_size * sizeof(uint32_t)` and `attribute_vector_size * sizeof(uint16_t)`.  Instead of the hard-coded `uintX` values this should depend on the data types used for dictionary and attribute vector. (Our code thus should currently break for DictionarySegments with more or less values than in our example.)

```cpp

auto dictionary_values = pmr_vector<int32_t>(dictionary_size);
memcpy(dictionary_values.data(), &map[header_offset + segment_element_offset_index + 3], dictionary_size * sizeof(uint32_t));
auto dictionary = std::make_shared<pmr_vector<int32_t>>(dictionary_values);

auto attribute_values = pmr_vector<uint16_t>(attribute_vector_size);
memcpy(attribute_values.data(), &map[header_offset + segment_element_offset_index + 3 + dictionary_size], attribute_vector_size * sizeof(uint16_t));
auto attribute_vector = std::make_shared<FixedWidthIntegerVector<uint16_t>>(attribute_values);
```



PS: I am not sure but does perhaps the last commit `7fb0d12803ed5e38aa8a90c9c94563d73e2291ae` 

> Refactor: Make file_header use uint32_t consistently
Previously two values of the file header were stored as uint16_t and the rest as uint32_t, making various calculations necessary to obtain the right values from a map. As we are talking about additional 4 Bytes per File, I am suggesting just storing the whole header in uint32_t format.

have something to do with this?

**Comment by rrcomtech** [comment]
@phoeinx I believe this was one of the main things, where I got confused. But I guess it was never a bug. Also I think I got confused during debugging and believed I found something 😄 But these values are indeed 2 Byte, not 4 as I thought (see image). 

![image](https://user-images.githubusercontent.com/50635122/218140301-50a14d93-78e4-42ee-b349-da62b76aabf7.png)

And you are totally right, that we are still hard coding data types. There, we have to have a closer look on. Probably this will already become much easier, once we do not map the whole file at once anymore.
